### ISSUE TITLE
Error in load

### ISSUE THREAD

**Issue by nchpmn** [mwunsch/tumblr#14]
Firstly, let me just dump the command line output here:

```
C:\Users\Nathan\Dropbox\Documents\Blog Posts>tumblr -q 004*
Email Address:  [EMAIL ADDRESS REMOVED]
Password:
C:/Ruby187/lib/ruby/1.8/yaml.rb:133:in `load': syntax error on line 5, col 23: `t
itle: Internet Stores: Not actaully destroying retailers?' (ArgumentError)
        from C:/Ruby187/lib/ruby/1.8/yaml.rb:133:in `load'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/tumblr-rb-1.3.0/lib/tumblr.rb:75:i
n `parse'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/tumblr-rb-1.3.0/bin/tumblr:125
        from C:/Ruby187/bin/tumblr:19:in `load'
        from C:/Ruby187/bin/tumblr:19
```

I've tried uninstalling and reinstallig the gem, but to no avail. I know how much of a b##ch Ruby is on Windows, so it may just be that. However it was working fine for the first `.markdown` file 'upload' a few days prior.

If you need more info, just ask.

System Specs:
- Windows 7
- Ruby 1.8.7

**Comment by nchpmn** [comment]
So I upgraded to Ruby 1.9.2, but I'm still getting a similar error:

```
C:\Users\Nathan\Dropbox\Documents\Blog Posts>tumblr 004*
Email Address:  [EMAIL ADDRESS REMOVED]
Password:
C:/Ruby192/lib/ruby/1.9.1/syck.rb:135:in `load': syntax error on line 5, col 23:
`title: Internet Stores: Not actaully destroying retailers?' (ArgumentError)
        from C:/Ruby192/lib/ruby/1.9.1/syck.rb:135:in `load'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tumblr-rb-1.3.0/lib/tumblr.rb:75
:in `parse'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tumblr-rb-1.3.0/bin/tumblr:125:i
n `<top (required)>'
        from C:/Ruby192/bin/tumblr:19:in `load'
        from C:/Ruby192/bin/tumblr:19:in `<main>'
```

It looks the same to me, so...?

**Comment by nchpmn** [comment]
...And now it works again. Hmm...

```
C:\Users\Nathan\Dropbox\Documents\Blog Posts>tumblr 006*
Email Address:  [EMAIL ADDRESS REMOVED]
Password:
Published to Tumblr. The ID for this post is: 8580281009
```

Could it possibly be that having the file open in a text editor was causing the error?

**Comment by nchpmn** [comment]
> Could it possibly be that having the file open in a text editor was causing the error?

Nope, evidently not. With the text editor, Dropbox and explorer windows closed, the same error (as far as I can tell)...

```

C:\Users\Nathan\Dropbox\Documents\Blog Posts>tumblr 010*
Email Address:  [EMAIL ADDRESS REMOVED]
Password:
C:/Ruby192/lib/ruby/1.9.1/syck.rb:135:in `load': syntax error on line 5, col 45:
`title: Books I Love (In No Particular Order): #1' (ArgumentError)
        from C:/Ruby192/lib/ruby/1.9.1/syck.rb:135:in `load'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tumblr-rb-1.3.0/lib/tumblr.rb:75
:in `parse'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tumblr-rb-1.3.0/bin/tumblr:125:i
n `<top (required)>'
        from C:/Ruby192/bin/tumblr:19:in `load'
        from C:/Ruby192/bin/tumblr:19:in `<main>'
```

Hmm... any ideas?

**UPDATE:** Just had a thought, is it an illegal character in the title of the post? The colon, for example, is present in both of the post titles in which I've had this error. Let me do a couple of tests and find out...

**Comment by nchpmn** [comment]
> UPDATE: Just had a thought, is it an illegal character in the title of the post? The colon, for example, is present in both of the post titles in which I've had this error. Let me do a couple of tests and find out...

Yes, this is exactly what caused the error.

```
C:\Users\Nathan\Dropbox\Documents\Blog Posts>tumblr 010*
Email Address:  [ADDRESS REMOVED]
Password:
Published to Tumblr. The ID for this post is: 9058459619
```

So all's good. And I've talked myself into fixing this problem. Awesome.
