### ISSUE TITLE
Please add instructions for installing the gem (or maybe I'm just really dumb)

### ISSUE THREAD

**Issue by rrthomas** [mwunsch/tumblr#21]
I'm a Ruby-noob, and I wanted to install the gem so I can just run "tumblr" rather than "bundle exec bin/tumblr" (which works fine but is a mouthful and has to be executed from the right directory). So I ran:

gem build tumblr-rb.gemspec
gem install tumblr-rb-2.0.0.alpha.gem

and that seemed to work. But if I now run, say, tumblr authorize, I get:

tumblr pipe requires at least 0 argument: "tumblr pipe".

which is a bit cryptic. Help?

**Comment by rrthomas** [comment]
Unfortunately, the problem persists. I check out the latest git, and with GEM_HOME=$HOME/.gem/ruby/1.9.1 (which matches the gem path for my home directory reported by "gem env") I run

rake install

After this, I get exactly the same error as before. (Running with bundler works fine.)

**Comment by rrthomas** [comment]
I get the same problem if I install from rubygems using

gem install tumbr-rb

Things are more mixed with other gems installed as dependencies of tumblr-rb: if I run "thor", it seems to work; if I run rake2thor (the only other executable installed by "gem install tumblr-rb") I get an error:

```
$ rake2thor 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- ruby2ruby (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/rrt/.gem/ruby/1.9.1/gems/thor-0.16.0/bin/rake2thor:3:in `<top (required)>'
    from /home/rrt/.gem/ruby/1.9.1/bin/rake2thor:23:in `load'
    from /home/rrt/.gem/ruby/1.9.1/bin/rake2thor:23:in `<main>'
```

but this appears justified, as I can't find ruby2ruby installed, so I guess it's a missing dependency in the thor gem?

**Comment by rrthomas** [comment]
(If I install ruby2ruby then it wants parse_tree; if I install that it tells me that ParseTree doesn't work with ruby 1.9.3. I don't suppose this is the problem with tumblr-rb, since it does work fine, just not from the standalone binary.

**Comment by rrthomas** [comment]
imkmf said:

> @rrthomas – sounds like there's a doozy of problems going on. My first suggestion: do a clean install of Ruby (if you can, use rvm and grab a 1.9 build) and then do gem install tumblr-rb. I've done this on my machine and haven't had any problems. Building this gem from the git repo is probably more work than needed – there aren't any outstanding changes AFAIK since some changes of mine that @mwunsch added to the gem a couple months ago. You should just be able to do gem install, which will take care of putting it in the proper place for you to just run tumblr at the command-line.
> 
> If you've done this already, apologies, just trying to get a sense of what part of the process is fouled up for you. Thanks!

Thanks very much for offering to look into this. I use Ubuntu 12.10's provided ruby1.9.3.194, setting GEM_HOME to $HOME/.gem/ruby/1.9.1 [sic, this is a path that is built in to the build of gem], and rm -rf'ing $HOME/.gem before I start. Then:

```
$ gem install tumblr-rb
Fetching: addressable-2.3.3.gem (100%)
Fetching: promise-0.3.0.gem (100%)
Fetching: simple_oauth-0.1.9.gem (100%)
Fetching: weary-1.1.2.gem (100%)
Fetching: thor-0.16.0.gem (100%)
Fetching: tumblr-rb-2.0.0.gem (100%)
Fetching: rack-protection-1.5.0.gem (100%)
Successfully installed addressable-2.3.3
Successfully installed promise-0.3.0
Successfully installed simple_oauth-0.1.9
Successfully installed weary-1.1.2
Successfully installed thor-0.16.0
Successfully installed tumblr-rb-2.0.0
Successfully installed rack-protection-1.5.0
7 gems installed
Installing ri documentation for addressable-2.3.3...
Installing ri documentation for promise-0.3.0...
Installing ri documentation for simple_oauth-0.1.9...
Installing ri documentation for weary-1.1.2...
Installing ri documentation for thor-0.16.0...
Installing ri documentation for tumblr-rb-2.0.0...
Installing ri documentation for rack-protection-1.5.0...
Installing RDoc documentation for addressable-2.3.3...
Installing RDoc documentation for promise-0.3.0...
Installing RDoc documentation for simple_oauth-0.1.9...
Installing RDoc documentation for weary-1.1.2...
Installing RDoc documentation for thor-0.16.0...
Installing RDoc documentation for tumblr-rb-2.0.0...
Installing RDoc documentation for rack-protection-1.5.0...
$ tumblr
Tasks:
  tumblr authorize                     # Authenticate and authorize the cli to post on your behalf
  tumblr delete POST_ID                # Delete a post
  tumblr edit POST_ID                  # Edit a post
  tumblr fetch POST_ID                 # Fetch a post and write out its serialized form.
  tumblr help [TASK]                   # Describe available tasks or one specific task
  tumblr pipe                          # Pipe post content in from STDIN
  tumblr post <POST> | <FILE> | <URL>  # Posts to tumblr
  tumblr version                       # Print Tumblr version information

Options:
  [--credentials=CREDENTIALS]  # The file path where your Tumblr OAuth keys are stored. Defaults to     ~/.tumblr.
  [--host=HOST]                # The hostname of the blog you want to post to i.e. "YOUR-NAME.tumblr.com"

$ tumblr version
tumblr pipe requires at least 0 argument: "tumblr pipe".
```
