### ISSUE TITLE
tumblr backup fails

### ISSUE THREAD

**Issue by wylieconlon** [mwunsch/tumblr#35]
I was running `tumblr backup`, after installing it via homebrew per [your instructions](http://mwunsch.tumblr.com/post/50840768162/backup-your-tumblr-with-tumblr-rb-v2-1-0) and found this error. It successfully backed up 340 posts before this:

```
/usr/local/Cellar/tumblr-rb/2.1.0/gems/promise-0.3.0/lib/future.rb:34:in `join': thread 0x108690808 tried to join itself (ThreadError)
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/promise-0.3.0/lib/future.rb:34:in `join'
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/promise-0.3.0/lib/future.rb:34:in `__force__'
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/promise-0.3.0/lib/promise.rb:89:in `method_missing'
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/tumblr-rb-2.1.0/lib/tumblr/command_line_interface.rb:154:in `backup'
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/tumblr-rb-2.1.0/lib/tumblr/command_line_interface.rb:171:in `backup'
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `__send__'
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
  from /usr/local/Cellar/tumblr-rb/2.1.0/gems/tumblr-rb-2.1.0/bin/tumblr:5
  from /usr/local/bin/tumblr:4:in `load'
  from /usr/local/bin/tumblr:4
```

**Comment by mwunsch** [comment]
This is a bug from deep within a lib dependency. Can you replicate it when you run the script again?

**Comment by wylieconlon** [comment]
Yes, I replicate it every time running ruby 1.8.7 (default with my computer). Using ruby 1.9.3 seems to fix the problem. Seeing that, I'm not sure that this is a real bug.

**Comment by mwunsch** [comment]
@wylieconlon I think it's a much larger issue with asynchronous behavior in Tumblr's http client library, Weary.
