### ISSUE TITLE
cannot load multi_json

### ISSUE THREAD

**Issue by ajwaxman** [mwunsch/tumblr#40]
Hey, awesome gem, thanks. I'm having a weird beginner issue - just want to see if someone can recreate it or point me in the right direction.

when I run `tumblr post 'test' --host=http://myblog.tumblr.com` the post works and is submitted correctly but I get an error at the end that says:

```
/Users/awaxman/.rvm/gems/ruby-1.9.3-p429/gems/weary-1.1.3/lib/weary/response.rb:59:in `parse': cannot load such file -- multi_json (LoadError)
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/gems/promise-0.3.0/lib/promise.rb:89:in `method_missing'
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/gems/tumblr-rb-2.1.1/lib/tumblr/command_line_interface.rb:78:in `post'
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/gems/tumblr-rb-2.1.1/bin/tumblr:5:in `<top (required)>'
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/bin/tumblr:23:in `load'
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/bin/tumblr:23:in `<main>'
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'
```

I'm using RVM `rvm 1.20.13 (stable) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]`

with a gem env of

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.3
  - RUBY VERSION: 1.9.3 (2013-05-15 patchlevel 429) [x86_64-darwin12.4.0]
  - INSTALLATION DIRECTORY: /Users/awaxman/.rvm/gems/ruby-1.9.3-p429
  - RUBY EXECUTABLE: /Users/awaxman/.rvm/rubies/ruby-1.9.3-p429/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/awaxman/.rvm/gems/ruby-1.9.3-p429/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-12
  - GEM PATHS:
     - /Users/awaxman/.rvm/gems/ruby-1.9.3-p429
     - /Users/awaxman/.rvm/gems/ruby-1.9.3-p429@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
```

gem version `tumblr-rb (2.1.1)`. Have tried installing multi_json, but that isn't fixing it.

```
json (1.8.0)
multi_json (1.7.6, 1.7.3)
```

Ideas? Thanks so much for any help. <3

**Comment by mwunsch** [comment]
This is the same issue in #36, and I need to fix the downstream cause in mwunsch/weary#39
